accounts:
  - name: technoking1
    coins: ["100000000dna"]
  - name: technoking2
    coins: ["100000000dna"]
validator:
  name: technoking1
  staked: "50000000dna"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: technoking2
  coins: ["100000dna"]
genesis:
  app_state:
    staking:
      params:
        bond_denom: "dna"
